# 1. Define the markdownlint Language Server configuration
[language-server.efm]
command = "efm-langserver"
args = ["-c", "/home/drew/.config/efm-langserver/config.yaml"]
root-indicators = [".git", ".markdownlint.json", ".markdownlintrc", "config.yaml"]

[language-server.vale-ls]
command = "vale-ls"

[language-server.ltex-ls-plus.config]
ltex.diagnosticSeverity = "warning"
ltex.ltex-ls.logLevel = "warning"
ltex.disabledRules = { "en-US" = ["PROFANITY"], "en-GB" = ["PROFANITY"] }
ltex.dictionary = { "en-US" = ["builtin"], "en-GB" = ["builtin"] }

# 2. Define the YAML configuration
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

# 3. Configure the Markdown Language settings
[[language]]
name = "markdown"
# language-servers = ["marksman", "vale-ls", { name = "efm", only-features = [ "diagnostics" ] }]
language-servers = ["marksman", "ltex-ls-plus"]
soft-wrap = { enable = true }
formatter = { command = "prettier", args = ["--parser", "markdown", "--prose-wrap", "never"] }
